/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JHJWrx0pB2O
 */
import { Button } from "@/components/ui/button"
import Image from "next/image"
import sqlite3 from "sqlite3";
import {open, Database} from 'sqlite';

let db: Database;

export async function Main() {
  if (!db) {
    db = await open({
      filename: "./hangman.db", 
      driver: sqlite3.Database,
    });
  }

  const word = await db.get("SELECT * FROM words ORDER BY RANDOM() LIMIT 1");
  
  return (
    <>
      <h1 className="mb-8 text-4xl font-bold">Hangman Game</h1>
      <div className="w-full max-w-md rounded-xl bg-gray-600 p-6 shadow-lg">
        <div className="mb-6 flex justify-center">
          <Image
            alt="Hangman Image"
            priority
            className="rounded-full"
            height="200"
            src="https://as2.ftcdn.net/v2/jpg/05/17/38/33/1000_F_517383341_8nWEFfM1KL3K5LNTjUDrne3x0kZiuxuj.jpg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
            }}
            width="200"
          />
        </div>
        <div className="mb-6">
          <p className="text-center text-xl font-semibold">Guess the word:</p>
          <p className="mt-2 text-center text-3xl font-bold">_ _ _ _ _ {word.word}</p>
        </div>
        <div className="grid grid-cols-8 gap-4">
          <Button className="py-2" variant="outline">
            A
          </Button>
          <Button className="py-2" variant="outline">
            B
          </Button>
          <Button className="py-2" variant="outline">
            C
          </Button>
          <Button className="py-2" variant="outline">
            D
          </Button>
          <Button className="py-2" variant="outline">
            E
          </Button>
          <Button className="py-2" variant="outline">
            F
          </Button>
          <Button className="py-2" variant="outline">
            G
          </Button>
          <Button className="py-2" variant="outline">
            H
          </Button>
          <Button className="py-2" variant="outline">
            I
          </Button>
          <Button className="py-2" variant="outline">
            J
          </Button>
          <Button className="py-2" variant="outline">
            K
          </Button>
          <Button className="py-2" variant="outline">
            L
          </Button>
          <Button className="py-2" variant="outline">
            M
          </Button>
          <Button className="py-2" variant="outline">
            N
          </Button>
          <Button className="py-2" variant="outline">
            O
          </Button>
          <Button className="py-2" variant="outline">
            P
          </Button>
          <Button className="py-2" variant="outline">
            Q
          </Button>
          <Button className="py-2" variant="outline">
            R
          </Button>
          <Button className="py-2" variant="outline">
            S
          </Button>
          <Button className="py-2" variant="outline">
            T
          </Button>
          <Button className="py-2" variant="outline">
            U
          </Button>
          <Button className="py-2" variant="outline">
            V
          </Button>
          <Button className="py-2" variant="outline">
            W
          </Button>
          <Button className="py-2" variant="outline">
            X
          </Button>
          <Button className="py-2" variant="outline">
            Y
          </Button>
          <Button className="py-2" variant="outline">
            Z
          </Button>
        </div>
      </div>
    </>
  )
}
